### ISSUE TITLE
缺少 Cargo.lock

### ISSUE THREAD

**Issue by sansx** [PrivateRookie/enlighten#2]
嗨，大佬，我最近把古诗文的api还原了，现在想跑一下你的项目试试，但是编译的时候报错了。
```
error[E0432]: unresolved import `syn::export`
  --> ~/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/enumset_derive-0.4.4/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`
```
查了一下因为这个`syn`依赖更新变化太大导致的，由于没有lock文件，无法确定`syn`版本

**Comment by PrivateRookie** [comment]
虽然指定了 cursive 的小版本, 但不知道为什么 cursive 自己版本依赖没控制好. 我升级了 cursive 14 -> 16, 现在应该编译通过了, 不过会有不少warning, 你先看着改改吧

**Comment by sansx** [comment]
好的，可以了。官方接口的示例里面也没有显示返回的数据格式，我照着大佬的代码改了一下接口返回的结构，已经可以跑起来了，哈哈。
我为这个项目写了的一个[api 服务](https://github.com/sansx/cn_poems_api)，和一个[把json导入到数据库](https://github.com/sansx/cn_poem_json_to_db)的仓库，这俩后续还有不少要优化的😆
![poem](https://tva1.sinaimg.cn/large/008eGmZEgy1gp1vywe7wfg30dc095npf.gif)

**Comment by sansx** [comment]
api url不知道编译完之后还有什么办法改变，如果可以通过[dotven](https://crates.io/crates/dotenv)，从外部环境获取就好了。
我晚些时候再仔细看看大佬的源码。

**Comment by sansx** [comment]
额，对了，问一下大佬，后续有更新的计划吗，可以的话我想帮一下忙。

**Comment by PrivateRookie** [comment]
抱歉, 最近没有太多精力在这个项目上, 这个项目是我学Rust不久后的一个练手项目, 写的也不是很好, 你可以fork一份然后自己改改.

**Comment by sansx** [comment]
嗯，我也是初学最近才开始做rust项目练手，一开始看了大佬的博客，觉得迷之亲切，想着是最好是可以和大佬参与点项目学的快一点，有点可惜，最后想问一下，大佬方便给个联系方式吗，这个issue我晚上就关掉。

**Comment by PrivateRookie** [comment]
可以加入Rust的飞书群 https://applink.feishu.cn/TeLAcbDR  和 https://applink.feishu.cn/TeLD868w, 然后搜索 PrivateRookie 用户就可以加上我. 飞书群挺活跃的, 还有定期分享, 我也经常在线的.

**Comment by sansx** [comment]
好，谢谢。:D
